export const deliveries = [
  {
    id: "DEL-001",
    customer: { name: "Ravi Kumar", phone: "+91 98765 43210", address: "12, MG Road, Bengaluru" },
    driver: { name: "Suresh B", vehicle: "KA-01-AB-1234" },
    status: "in_transit",
    riskScore: 91,
    riskReason: "Heavy rain on route + customer missed 2 previous deliveries",
    signals: { weather: 88, traffic: 72, customerHistory: 90 },
    whatsappLog: [
      { from: "bot", message: "Hi Ravi, your order is on the way. Will you be available at 2pm?", time: "1:32 PM" },
      { from: "customer", message: "I'm not home, please leave at the gate", time: "1:35 PM" },
      { from: "bot", message: "Got it! Driver has been instructed to leave at the gate.", time: "1:35 PM" },
    ],
    eta: "2:10 PM",
    coords: { x: 180, y: 110 },
  },
  {
    id: "DEL-002",
    customer: { name: "Priya Nair", phone: "+91 91234 56789", address: "45, Koramangala, Bengaluru" },
    driver: { name: "Ramesh K", vehicle: "KA-03-CD-5678" },
    status: "in_transit",
    riskScore: 82,
    riskReason: "Severe traffic jam on Hosur Road, 40min delay likely",
    signals: { weather: 45, traffic: 95, customerHistory: 20 },
    whatsappLog: [
      { from: "bot", message: "Hi Priya, your delivery is delayed due to traffic. New ETA is 3:15 PM.", time: "2:10 PM" },
      { from: "customer", message: "Ok no problem", time: "2:12 PM" },
    ],
    eta: "3:15 PM",
    coords: { x: 420, y: 210 },
  },
  {
    id: "DEL-003",
    customer: { name: "Arjun Singh", phone: "+91 99887 76655", address: "8, Indiranagar, Bengaluru" },
    driver: { name: "Vijay M", vehicle: "KA-05-EF-9012" },
    status: "in_transit",
    riskScore: 61,
    riskReason: "Moderate rain forecast, route passable",
    signals: { weather: 65, traffic: 40, customerHistory: 10 },
    whatsappLog: [],
    eta: "2:45 PM",
    coords: { x: 560, y: 100 },
  },
  {
    id: "DEL-004",
    customer: { name: "Sneha Rao", phone: "+91 88776 65544", address: "22, HSR Layout, Bengaluru" },
    driver: { name: "Kumar P", vehicle: "KA-02-GH-3456" },
    status: "delivered",
    riskScore: 34,
    riskReason: "Clear conditions, customer responsive",
    signals: { weather: 20, traffic: 30, customerHistory: 5 },
    whatsappLog: [],
    eta: "1:30 PM",
    coords: { x: 280, y: 260 },
  },
  {
    id: "DEL-005",
    customer: { name: "Kiran Mehta", phone: "+91 77665 54433", address: "3, Whitefield, Bengaluru" },
    driver: { name: "Anil S", vehicle: "KA-04-IJ-7890" },
    status: "in_transit",
    riskScore: 78,
    riskReason: "Customer unresponsive in 3 past deliveries",
    signals: { weather: 30, traffic: 55, customerHistory: 85 },
    whatsappLog: [
      { from: "bot", message: "Hi Kiran, confirming your delivery today at 4pm. Please confirm.", time: "3:00 PM" },
    ],
    eta: "4:00 PM",
    coords: { x: 90, y: 230 },
  },
  {
    id: "DEL-006",
    customer: { name: "Meera Pillai", phone: "+91 66554 43322", address: "17, JP Nagar, Bengaluru" },
    driver: { name: "Raju T", vehicle: "KA-06-KL-2345" },
    status: "failed",
    riskScore: 95,
    riskReason: "Customer unreachable + flooded road on route",
    signals: { weather: 98, traffic: 88, customerHistory: 95 },
    whatsappLog: [
      { from: "bot", message: "Hi Meera, your delivery is scheduled for today. Are you available?", time: "11:00 AM" },
      { from: "bot", message: "Hi Meera, we tried reaching you. Please reschedule.", time: "1:00 PM" },
    ],
    eta: "—",
    coords: { x: 500, y: 280 },
  },
];

export const stats = {
  total: 248,
  highRisk: 12,
  autoResolved: 9,
  failed: 2,
};

export const user = {
  name: "Anwita R",
  role: "Senior Dispatcher",
  company: "Swiftlane Operations",
  avatar: "AR",
};